import type { Metadata } from "next";
import {
  // Inter,
  Montserrat,
  // Nunito,
} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/custom/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Cửa Hàng",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  variable: "--font-montserrat-mono",
  subsets: ["latin"],
});

// const nunito = Nunito({
//   variable: "--font-nunito-mono",
//   subsets: ["latin"],
// });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className={`${montserrat.className} flex flex-col overflow-y-auto overflow-x-hidden antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader showSpinner={false} />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
